### ISSUE TITLE
Seperate out urban dictionary call from the main python script

### ISSUE THREAD

**Issue by nootanghimire** [dafuq-is/backend#2]
Start separating out the codebase into a nice structure.

**Comment by Avasz** [comment]
Do you propose something like dafuq.is/ud/word?

**Comment by nootanghimire** [comment]
@Avasz more like: `dafuq.is/word/source`, but we make source optional. 

But I was thinking if we could make this script/app generic so that it can be reused in other parts like bots or other scripts or whatnot.
